### ISSUE TITLE
Stesura sezione "Qualità di prodotto"

### ISSUE THREAD

**Issue by casYy** [SWEasabi/piano-di-qualifica#6]
Stesura di una sezione che descriva gli standard di qualità del prodotto utilizzando le sezioni già presenti nella scaletta.

**Comment by Giorgio-Zarantonello** [comment]
[https://github.com/SWEasabi/piano-di-qualifica/blob/feature/prodotto/src-doc/contenuti/qualita-di-prodotto.tex](url)

@casYy ecco il tag per quando hai modo di dare una opinione alla draft
