### ISSUE TITLE
Alcuni test da inserire

### ISSUE THREAD

**Issue by alessandro-massarenti** [SWEasabi/piano-di-qualifica#7]
Non sono sicuro di dove questi test vadano inseriti, però sicuramente sono da inserire:

- Test funzionali
- Test strutturali
- Test di accettazione
- Test di non regressione
- Calcolo della complessità ciclomatica
- Analisi dinamica
- Analisi statica

Questi test e analisi vanno inseriti relativamente alla codifica e relativamente alla stesura della documentazione.

@casYy Tu che sei ferrato su questa parte, se riuscissi a darne un'opinione/indicazione sarebbe fantastico.

Grazie.

**Comment by casYy** [comment]
i test sono parte del pdq

**Comment by alessandro-massarenti** [comment]
A lezione il professore ha detto che sarebbe buona norma descriverli.

Infatti lo scopo del PdQ è "fissare delle metriche precise e quantitative". _Da appunti presi a lezione_

**Comment by alessandro-massarenti** [comment]
> Va ben, allora provo a risponderti @alessandro-massarenti
> 
> * Tendenzialmente i test possono essere strutturali o funzionali sì ma questo non dovrebbe precluderli dall'essere test di unità etc. se ben ricordo e non è necessario specificarlo

Beh sarebbe bene dirlo soprattutto in relazione ai requisiti. Perché i test funzionali rispondono ad alcuni requisiti ed i test strutturali ad altri requisiti e alle specifiche architetturali.

> * test di accettazione e (immagino tu intenda) regressione hanno già la loro sezione nel documento, quindi sono apposto, anche se questi sono decisamente parecchio più avanti per noi

La sezione è già aggiunta? in ogni caso sarebbe da capire in quale versione del documento rilasciare questa parte.

Se prima o dopo la versione 1.0

> * per quanto riguarda la ciclomatica non ti saprei dire, sei sicuro che il professore la voglia descritta?

Secondo me vuole una descrizione sul come la attuiamo almeno.

> * anche qui non dovrebbe esserci bisogno di specificare nel documento per quanto riguarda statica/dinamica

In generale ho visto farlo, magari aggiungiamo nella spiegazione degli specifici test e analisi.


Comunque come prima dicevo in generale sarebbe da capire queste parti in che versione del documento rilasciarle e in che qualità e quantità.
